// CREATE A USER
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Widya Sabina",
    "email": "widya@gmail.com",
    "password": "wiwid123",
    "confPassword": "wiwid123",
    "role": "user"
}

###
// GET ALL USERS
GET http://localhost:8000/users

###
// GET SINGLE USER
GET http://localhost:8000/users/343fd55d-afdd-4c48-9f70-f31cbd42d125

###
// UPDATE A USER
PATCH  http://localhost:8000/users/343fd55d-afdd-4c48-9f70-f31cbd42d125
Content-Type: application/json

{
    "name": "Annisa Nurhaniyah Iskandar",
    "email": "annisa@gmail.com",
    "password": "icha1919",
    "confPassword": "icha1919",
    "role": "admin"
}

###
//DELETE A USER
DELETE http://localhost:8000/users/bb8cbf3b-8e88-4e49-ac95-549cf0da235a

###
// LOGIN
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "annisa@gmail.com",
    "password": "icha1919"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "widya@gmail.com",
    "password": "wiwid123"
}

###
GET http://localhost:8000/me

###
DELETE http://localhost:8000/logout


###
// GET ALL ARTICLES
GET http://localhost:8000/articles

###
// GET SINGLE ARTICLES
GET http://localhost:8000/articles/27510ddb-e28a-405a-9b2b-6c44b1557a4e

###
// POST DATA ARTICLE
POST http://localhost:8000/articles
Content-Type: application/json

{
    "title": "Judul 02",
    "desc": "Ini adalah artikel yang kedua dibuat oleh user"
}

###
// UPDATE DATA ARTICLE
PATCH http://localhost:8000/articles/27510ddb-e28a-405a-9b2b-6c44b1557a4e
Content-Type: application/json

{
    "title": "Judul 01",
    "desc": "Ini adalah artikel pertama yang telah direvisi kembali"
}

###
//DELETE A ARTICLE
DELETE http://localhost:8000/articles/27510ddb-e28a-405a-9b2b-6c44b1557a4e