// CREATE A USER
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Widya Sabina",
    "email": "widyas@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
// GET ALL USERS
GET http://localhost:8000/users

###
// GET SINGLE USER
GET http://localhost:8000/users/caca7d23-d809-465e-bd72-0463836b9ca7

###
// UPDATE A USER
PATCH  http://localhost:8000/users/caca7d23-d809-465e-bd72-0463836b9ca7
Content-Type: application/json

{
    "name": "Annisa Nurhaniyah Iskandar",
    "email": "annisa@gmail.com",
    "password": "icha1919",
    "confPassword": "icha1919",
    "role": "admin"
}

###
//DELETE A USER
DELETE http://localhost:8000/users/bb8cbf3b-8e88-4e49-ac95-549cf0da235a

###
// LOGIN
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "annisanur@gmail.com",
    "password": "p@ssword"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "widyas@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8000/me

###
DELETE http://localhost:8000/logout


###
// GET ALL HALLS
GET http://localhost:8000/halls

###
// GET SINGLE HALLS
GET http://localhost:8000/halls

###
// POST DATA HALLS
POST http://localhost:8000/halls
Content-Type: application/json

{
    "title": "Judul 02",
    "desc": "Ini adalah artikel yang kedua dibuat oleh user",
    "photo": ""
}

###
// UPDATE DATA HALLS
PATCH http://localhost:8000/halls/
Content-Type: application/json

{
    "title": "Judul 01",
    "desc": "Ini adalah artikel pertama yang telah direvisi kembali"
}

###
//DELETE A HALLS
DELETE http://localhost:8000/halls